services:
  - type: web
    name: fan-olimpiada
    runtime: node
    rootDir: .
    buildCommand: npm run build:all
    startCommand: npm run render-start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
