import { useRef, useState } from 'react';
import api from '../api';
import { useStore } from '../store';
import { useLanguage } from '../i18n';
import Icon from '../components/Icon';

export default function Import() {
 const {subjectId,subjects}=useStore();const {t}=useLanguage();const [file,setFile]=useState(null),[result,setResult]=useState(null),[error,setError]=useState(''),[loading,setLoading]=useState(false);const inputRef=useRef();
 const submit=()=>{if(!file)return setError(t('Fayl tanlanmagan'));if(!subjectId)return setError(t('Fan tanlanmagan'));setError('');setResult(null);setLoading(true);const fd=new FormData();fd.append('file',file);fd.append('subjectId',subjectId);api.post('/api/import',fd).then(r=>{setResult(r);setFile(null);if(inputRef.current)inputRef.current.value=''}).catch(e=>setError(e.message)).finally(()=>setLoading(false));};
 return <div><div className="page-head"><div><h1 className="page-title">{t('Savollar importi')}</h1><p className="page-desc">{t('Excel yoki CSV fayl orqali ko‘p sonli savollarni tez yuklang.')}</p></div></div>{error&&<div className="alert alert-error"><Icon name="alert" size={16}/>{error}</div>}{result&&<div className="alert alert-success"><Icon name="checkCircle" size={16}/><div><strong>{result.inserted} / {result.total} {t('ta savol qo‘shildi.')}</strong>{result.errors.length>0&&<ul className="error-list">{result.errors.map((e,i)=><li key={i}>{e}</li>)}</ul>}</div></div>}
 <div className="grid-2"><section className="card"><div className="card-title"><Icon name="upload"/> {t('Fayl yuklash')}</div><div className="field-group"><label className="field">{t('Faol fan')}</label><select className="select full-width" value={subjectId} disabled>{subjects.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><div className="field-group"><label className="field">{t('Fayl (.xlsx, .csv)')}</label><input ref={inputRef} className="input file-input" type="file" accept=".xlsx,.xls,.csv" onChange={e=>setFile(e.target.files[0]||null)}/>{file&&<div className="file-selected"><Icon name="file" size={16}/><span>{file.name}</span></div>}</div><button className="btn btn-primary" disabled={loading||!file} onClick={submit}>{loading?t('Yuklanmoqda...'):<><Icon name="upload" size={16}/> {t('Import qilish')}</>}</button><div className="import-template"><a className="btn btn-secondary btn-sm" href="/api/import-template"><Icon name="file" size={14}/> {t('Namuna shablonni yuklab olish')}</a></div></section>
 <section className="card"><div className="card-title"><Icon name="file"/> {t('Fayl formati')}</div><p className="muted-paragraph">{t('Birinchi qatorda ustun nomlari, keyingi qatorlarda savollar bo‘lishi kerak.')}</p><div className="table-wrap"><table className="table"><thead><tr><th>{t('Ustun')}</th><th>{t('Tavsif')}</th><th>{t('Misol')}</th></tr></thead><tbody>{[['year','Olimpiada yili','2024'],['stage','Bosqich','Viloyat'],['topic','Mavzu','Algoritmlar'],['question','Savol matni','2+2 nechaga teng?'],['a, b, c, d','Javob variantlari','3, 4, 5, 6'],['correct','To‘g‘ri javob','B'],['note','Izoh / manba','1-tur 3-savol']].map(r=><tr key={r[0]}><td><span className="code-chip">{r[0]}</span></td><td>{t(r[1])}</td><td>{r[2]}</td></tr>)}</tbody></table></div><div className="info-box"><Icon name="info" size={16}/><span>{t('Yangi yil yoki mavzu avtomatik yaratiladi. Xato qatorlar hisobotda ko‘rsatiladi.')}</span></div></section></div></div>;
}
