import { useEffect, useState } from 'react';
import api from '../api';
import { useStore } from '../store';
import { useLanguage } from '../i18n';
import Icon from '../components/Icon';

const LETTERS = ['A', 'B', 'C', 'D'];
const EMPTY_FORM = { yearId: '', topicId: '', questionText: '', imageUrl: '', options: ['', '', '', ''], correctAnswer: 0, sourceNote: '' };

export default function Questions() {
  const { subjectId } = useStore();
  const { t } = useLanguage();
  const [years,setYears]=useState([]),[topics,setTopics]=useState([]),[questions,setQuestions]=useState([]),[filterYear,setFilterYear]=useState(''),[filterTopic,setFilterTopic]=useState(''),[search,setSearch]=useState(''),[modal,setModal]=useState(null),[error,setError]=useState(''),[uploading,setUploading]=useState(false),[saving,setSaving]=useState(false);
  const load = () => { if (!subjectId) return; Promise.all([api.get(`/api/years?subjectId=${subjectId}`),api.get(`/api/topics?subjectId=${subjectId}`)]).then(([y,tp])=>{setYears(y);setTopics(tp)}); const p=new URLSearchParams({subjectId}); if(filterYear)p.set('yearId',filterYear);if(filterTopic)p.set('topicId',filterTopic);if(search.trim())p.set('search',search.trim());api.get(`/api/questions?${p}`).then(setQuestions).catch(()=>setQuestions([])); };
  useEffect(load,[subjectId,filterYear,filterTopic]);
  const openAdd=()=>{setError('');setModal({mode:'add',id:null,form:{...EMPTY_FORM,yearId:years[0]?.id||''}})};
  const openEdit=q=>{setError('');setModal({mode:'edit',id:q.id,form:{yearId:q.year_id,topicId:q.topic_id||'',questionText:q.question_text,imageUrl:q.image_url||'',options:[...q.options],correctAnswer:q.correct_answer,sourceNote:q.source_note||''}})};
  const save=()=>{const {mode,id,form}=modal; if(!form.yearId||!form.questionText.trim()||form.options.some(o=>!o.trim())) return setError(t('Yil, savol matni va barcha variantlarni to‘ldiring.')); setSaving(true); const body={...form,yearId:Number(form.yearId),topicId:form.topicId?Number(form.topicId):null}; (mode==='add'?api.post('/api/questions',body):api.put(`/api/questions/${id}`,body)).then(()=>{setModal(null);load()}).catch(e=>setError(e.message)).finally(()=>setSaving(false));};
  const uploadImage=file=>{if(!file)return;setUploading(true);const fd=new FormData();fd.append('image',file);api.post('/api/upload',fd).then(r=>setModal(m=>({...m,form:{...m.form,imageUrl:r.url}}))).catch(e=>setError(e.message)).finally(()=>setUploading(false));};
  const remove=q=>{if(!window.confirm(t('Bu savolni o‘chirasizmi?')))return;api.del(`/api/questions/${q.id}`).then(load).catch(e=>setError(e.message));};
  const f=modal?.form;
  return <div>
    <div className="page-head"><div><h1 className="page-title">{t('Savollar bazasi')}</h1><p className="page-desc">{t('Savollarni qidiring, filtrlab ko‘ring va to‘g‘ridan-to‘g‘ri tahrirlang.')}</p></div><button className="btn btn-primary" onClick={openAdd}><Icon name="plus" size={16}/> {t('Yangi savol')}</button></div>
    {error&&!modal&&<div className="alert alert-error"><Icon name="alert" size={16}/>{error}</div>}
    <div className="card filter-card"><div className="toolbar"><div className="filter-field"><Icon name="filter" size={15}/><select className="select" value={filterYear} onChange={e=>setFilterYear(e.target.value)}><option value="">{t('Barcha yillar')}</option>{years.map(y=><option key={y.id} value={y.id}>{y.year} · {y.stage}</option>)}</select></div><div className="filter-field"><Icon name="tag" size={15}/><select className="select" value={filterTopic} onChange={e=>setFilterTopic(e.target.value)}><option value="">{t('Barcha mavzular')}</option>{topics.map(tp=><option key={tp.id} value={tp.id}>{tp.name}</option>)}</select></div><div className="search-field"><Icon name="search" size={16}/><input className="input" placeholder={t('Savol bo‘yicha qidirish...')} value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()}/></div><button className="btn btn-secondary" onClick={load}><Icon name="search" size={15}/> {t('Qidirish')}</button></div></div>
    <div className="card table-card">{!questions.length?<div className="empty"><div className="empty-icon"><Icon name="book" size={20}/></div>{t('Savollar topilmadi. Filtrlarni o‘zgartiring yoki yangi savol qo‘shing.')}</div>:<div className="table-wrap"><table className="table"><thead><tr><th>#</th><th>{t('Savol')}</th><th>{t('Mavzu')}</th><th>{t('Yil')}</th><th>{t('Amallar')}</th></tr></thead><tbody>{questions.map((q,i)=><tr key={q.id}><td className="table-number">{questions.length-i}</td><td><div className="question-cell">{q.image_url&&<img src={q.image_url} className="img-thumb" alt=""/>}<span className="question-text">{q.question_text.length>150?q.question_text.slice(0,150)+'…':q.question_text}</span></div></td><td>{q.topic_name?<span className="badge"><Icon name="tag" size={11}/>{q.topic_name}</span>:<span className="badge badge-gray">{t('Mavzusiz')}</span>}</td><td><span className="badge badge-gray">{q.year} · {q.stage}</span></td><td><div className="row-actions"><button className="btn btn-secondary btn-sm" onClick={()=>openEdit(q)}><Icon name="pencil" size={14}/> {t('Tahrirlash')}</button><button className="btn btn-danger btn-sm" onClick={()=>remove(q)}><Icon name="trash" size={14}/> {t('O‘chirish')}</button></div></td></tr>)}</tbody></table></div>}</div>
    {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}><div className="modal-head"><div><h3>{modal.mode==='add'?t('Yangi savol'):t('Savolni tahrirlash')}</h3><p className="muted-note">{t('Savol va javob variantlarini aniq kiriting.')}</p></div><button className="btn btn-ghost action-icon" onClick={()=>setModal(null)}><Icon name="x"/></button></div>{error&&<div className="alert alert-error"><Icon name="alert" size={16}/>{error}</div>}<div className="field-row"><div className="field-group"><label className="field">{t('Yil / bosqich *')}</label><select className="select full-width" value={f.yearId} onChange={e=>setModal({...modal,form:{...f,yearId:e.target.value}})}><option value="">{t('Tanlang...')}</option>{years.map(y=><option key={y.id} value={y.id}>{y.year} · {y.stage}</option>)}</select></div><div className="field-group"><label className="field">{t('Mavzu')}</label><select className="select full-width" value={f.topicId} onChange={e=>setModal({...modal,form:{...f,topicId:e.target.value}})}><option value="">{t('Mavzusiz')}</option>{topics.map(tp=><option key={tp.id} value={tp.id}>{tp.name}</option>)}</select></div></div><div className="field-group"><label className="field">{t('Savol matni *')}</label><textarea className="input full-width" rows={4} value={f.questionText} onChange={e=>setModal({...modal,form:{...f,questionText:e.target.value}})}/></div><div className="field-group"><label className="field">{t('Rasm')}</label><div className="upload-row"><input className="input file-input" type="file" accept="image/*" onChange={e=>uploadImage(e.target.files[0])}/>{uploading&&<span className="muted-note">{t('Yuklanmoqda...')}</span>}{f.imageUrl&&<img src={f.imageUrl} className="img-thumb" alt=""/>}</div></div><div className="field-group"><label className="field">{t('Variantlar * · to‘g‘ri javobni belgilang')}</label>{f.options.map((o,i)=><div className="form-option" key={i}><input type="radio" name="correct" checked={f.correctAnswer===i} onChange={()=>setModal({...modal,form:{...f,correctAnswer:i}})}/><span className="form-option-letter">{LETTERS[i]}</span><input className="input" value={o} placeholder={`${LETTERS[i]} varianti`} onChange={e=>{const options=[...f.options];options[i]=e.target.value;setModal({...modal,form:{...f,options}})}}/></div>)}</div><div className="field-group"><label className="field">{t('Manba / izoh')}</label><input className="input full-width" value={f.sourceNote} onChange={e=>setModal({...modal,form:{...f,sourceNote:e.target.value}})}/></div><div className="modal-actions"><button className="btn btn-secondary" onClick={()=>setModal(null)}>{t('Bekor qilish')}</button><button className="btn btn-primary" disabled={saving||uploading} onClick={save}>{saving?t('Saqlanmoqda...'):<><Icon name="check" size={16}/> {t('Saqlash')}</>}</button></div></div></div>}
  </div>;
}